version: "2"
services:
  mongodb:
    image: bitnami/mongodb:latest
    ports: [
      "27017:27017"
    ]
    volumes:
      - /data/db:/data/db
    environment:
      - MONGODB_USER=usuario
      - MONGODB_PASSWORD=senha
      - MONGODB_DATABASE=banco
      - MONGODB_ROOT_PASSWORD=senha_do_root
  web:
    build: .
    volumes:
      - ./:/app
    ports: [
      "3000:3000"
    ]
    depends_on:
      - mongodb